import type { Metadata } from "next";
import { ArrowRight, EnvelopeSimple, ShieldCheck } from "@phosphor-icons/react/dist/ssr";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { SUPPORT_EMAIL } from "@/content/site";

export const metadata: Metadata = { title: "Contact", description: "Contact Revenge Arc support.", alternates: { canonical: "/contact" } };

export default function ContactPage() {
  return <><PageHero eyebrow="Contact" title={<>Let&apos;s solve<br /><span className="text-gradient-cyan">the next thing.</span></>} description="One contact point for product support, privacy rights, deletion requests, safety reports, appeals, partnerships, and policy questions." /><section className="content-shell py-20 sm:py-28"><div className="grid max-w-5xl gap-4 md:grid-cols-[1.2fr_.8fr]"><a href={`mailto:${SUPPORT_EMAIL}`} className="hairline-panel flex min-h-48 items-center gap-5 rounded-2xl p-6 hover:border-cyan-300/30 sm:p-8"><span className="grid size-14 shrink-0 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><EnvelopeSimple size={28} aria-hidden="true" /></span><span><span className="block text-sm text-zinc-500">Email Revenge Arc</span><span className="mt-1 block break-all text-lg font-bold text-white sm:text-2xl">{SUPPORT_EMAIL}</span><span className="mt-3 block text-sm leading-6 text-zinc-400">Include the account email and a clear description, but never send a password, authentication code, full payment-card number, or unnecessary health information.</span></span></a><Link href="/legal" className="hairline-panel group flex min-h-48 flex-col rounded-2xl p-6 hover:border-violet-300/30 sm:p-8"><ShieldCheck size={28} className="text-violet-300" aria-hidden="true" /><span className="display-text mt-5 text-3xl font-bold uppercase text-white">Legal Center</span><span className="mt-2 text-sm leading-6 text-zinc-400">Review privacy, AI, safety, community, retention, subscription, and website policies.</span><span className="mt-auto flex items-center gap-2 pt-5 text-sm font-bold text-violet-300">Open policies <ArrowRight size={17} aria-hidden="true" className="transition-transform group-hover:translate-x-1" /></span></Link></div><div className="mt-6 max-w-3xl rounded-xl border border-amber-400/25 bg-amber-400/[0.06] p-4 text-sm leading-6 text-amber-100"><strong>Not for emergencies.</strong> This inbox is not continuously monitored. Contact local emergency services for immediate danger or urgent medical help.</div><p className="mt-5 max-w-2xl text-sm leading-6 text-zinc-500">Messages open in your email app and are not stored by this website. Response times may vary during launch periods.</p></section></>;
}
