create extension if not exists pgcrypto with schema extensions;

do $$ begin
  create type public.admin_role as enum ('owner', 'admin');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.creator_application_status as enum ('new', 'reviewing', 'approved', 'rejected');
exception when duplicate_object then null;
end $$;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.admin_role not null default 'admin',
  created_at timestamptz not null default now()
);

create table if not exists public.creator_applications (
  id uuid primary key default extensions.gen_random_uuid(),
  submitted_at timestamptz not null default now(),
  full_name text not null check (char_length(full_name) between 2 and 120),
  email text not null check (char_length(email) <= 254),
  phone text check (phone is null or char_length(phone) <= 40),
  desired_compensation text not null check (char_length(desired_compensation) <= 300),
  instagram text check (instagram is null or char_length(instagram) <= 80),
  tiktok text check (tiktok is null or char_length(tiktok) <= 80),
  motivation text not null check (char_length(motivation) between 40 and 2500),
  audience_description text not null check (char_length(audience_description) between 30 and 2500),
  consent_version text not null check (char_length(consent_version) <= 40),
  consented_at timestamptz not null,
  utm_source text check (utm_source is null or char_length(utm_source) <= 120),
  status public.creator_application_status not null default 'new',
  private_notes text not null default '' check (char_length(private_notes) <= 5000),
  reviewer uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  archived_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists creator_applications_email_lower_unique
  on public.creator_applications (lower(email));
create index if not exists creator_applications_status_submitted_idx
  on public.creator_applications (status, submitted_at desc);
create index if not exists creator_applications_archived_idx
  on public.creator_applications (archived_at) where archived_at is not null;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_name text not null check (event_name in ('page_view', 'app_store_click', 'pricing_plan_click', 'creator_cta', 'creator_form_start', 'creator_submission')),
  path text not null check (left(path, 1) = '/' and char_length(path) <= 300),
  referrer_host text check (referrer_host is null or char_length(referrer_host) <= 253),
  utm_source text check (utm_source is null or char_length(utm_source) <= 120),
  utm_medium text check (utm_medium is null or char_length(utm_medium) <= 120),
  utm_campaign text check (utm_campaign is null or char_length(utm_campaign) <= 120),
  utm_content text check (utm_content is null or char_length(utm_content) <= 120),
  utm_term text check (utm_term is null or char_length(utm_term) <= 120),
  device_class text not null check (device_class in ('mobile', 'tablet', 'desktop')),
  anonymous_daily_hash text not null check (char_length(anonymous_daily_hash) = 40),
  event_details jsonb not null default '{}'::jsonb,
  check (jsonb_typeof(event_details) = 'object' and octet_length(event_details::text) <= 4096)
);

create index if not exists analytics_events_occurred_idx on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_event_occurred_idx on public.analytics_events (event_name, occurred_at desc);
create index if not exists analytics_events_path_occurred_idx on public.analytics_events (path, occurred_at desc);

create table if not exists public.analytics_daily (
  aggregate_date date not null,
  event_name text not null,
  path text,
  referrer_host text,
  utm_campaign text,
  device_class text,
  event_count bigint not null,
  unique_visitors bigint not null,
  created_at timestamptz not null default now()
);

create unique index if not exists analytics_daily_dimensions_unique on public.analytics_daily (
  aggregate_date,
  event_name,
  coalesce(path, ''),
  coalesce(referrer_host, ''),
  coalesce(utm_campaign, ''),
  coalesce(device_class, '')
);
create index if not exists analytics_daily_date_idx on public.analytics_daily (aggregate_date desc);

create table if not exists public.rate_limit_buckets (
  bucket_key text not null,
  kind text not null,
  hit_count integer not null default 1,
  expires_at timestamptz not null,
  primary key (bucket_key, kind)
);
create index if not exists rate_limit_expiry_idx on public.rate_limit_buckets (expires_at);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists creator_applications_touch_updated_at on public.creator_applications;
create trigger creator_applications_touch_updated_at
before update on public.creator_applications
for each row execute function public.touch_updated_at();

create or replace function public.is_site_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_profiles
    where user_id = auth.uid() and role in ('owner', 'admin')
  );
$$;

revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to authenticated;

alter table public.admin_profiles enable row level security;
alter table public.creator_applications enable row level security;
alter table public.analytics_events enable row level security;
alter table public.analytics_daily enable row level security;
alter table public.rate_limit_buckets enable row level security;

drop policy if exists "admins read own profile" on public.admin_profiles;
create policy "admins read own profile" on public.admin_profiles for select to authenticated using (user_id = auth.uid());

drop policy if exists "admins read creator applications" on public.creator_applications;
create policy "admins read creator applications" on public.creator_applications for select to authenticated using (public.is_site_admin());
drop policy if exists "admins update creator applications" on public.creator_applications;
create policy "admins update creator applications" on public.creator_applications for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());
drop policy if exists "admins delete creator applications" on public.creator_applications;
create policy "admins delete creator applications" on public.creator_applications for delete to authenticated using (public.is_site_admin());

drop policy if exists "admins read analytics events" on public.analytics_events;
create policy "admins read analytics events" on public.analytics_events for select to authenticated using (public.is_site_admin());
drop policy if exists "admins read analytics daily" on public.analytics_daily;
create policy "admins read analytics daily" on public.analytics_daily for select to authenticated using (public.is_site_admin());

create or replace function public.consume_rate_limit(
  p_bucket_key text,
  p_kind text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_hits integer;
begin
  delete from public.rate_limit_buckets where expires_at <= now();
  insert into public.rate_limit_buckets (bucket_key, kind, hit_count, expires_at)
  values (p_bucket_key, p_kind, 1, now() + make_interval(secs => p_window_seconds))
  on conflict (bucket_key, kind) do update
    set hit_count = public.rate_limit_buckets.hit_count + 1
  returning hit_count into current_hits;
  return current_hits <= p_limit;
end;
$$;

revoke all on function public.consume_rate_limit(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, text, integer, integer) to service_role;

create or replace function public.aggregate_analytics_day(p_day date)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.analytics_daily where aggregate_date = p_day;
  insert into public.analytics_daily (
    aggregate_date, event_name, path, referrer_host, utm_campaign, device_class, event_count, unique_visitors
  )
  select
    p_day,
    event_name,
    path,
    referrer_host,
    utm_campaign,
    device_class,
    count(*),
    count(distinct anonymous_daily_hash)
  from public.analytics_events
  where occurred_at >= p_day::timestamptz
    and occurred_at < (p_day + 1)::timestamptz
  group by event_name, path, referrer_host, utm_campaign, device_class;
end;
$$;

create or replace function public.enforce_website_retention()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.analytics_events where occurred_at < now() - interval '90 days';
  delete from public.analytics_daily where aggregate_date < current_date - interval '24 months';
  delete from public.rate_limit_buckets where expires_at <= now();
end;
$$;

revoke all on function public.aggregate_analytics_day(date) from public, anon, authenticated;
revoke all on function public.enforce_website_retention() from public, anon, authenticated;
grant execute on function public.aggregate_analytics_day(date) to service_role;
grant execute on function public.enforce_website_retention() to service_role;

revoke all on table public.admin_profiles from anon;
revoke all on table public.creator_applications from anon;
revoke all on table public.analytics_events from anon;
revoke all on table public.analytics_daily from anon;
revoke all on table public.rate_limit_buckets from anon, authenticated;
